modLoader = "javafml"
loaderVersion = "[44,)"
license = "All Rights Reserved"
issueTrackerURL="https://github.com/PanSzelescik/colorize/issues"
[[mods]]
modId = "commandessentials"
version = "${version}"
displayName = "Command Essentials"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colorize"
authors = "PanSzelescik"
description = '''
Right click on the dye on some blocks to color them!
'''
[[dependencies.commandessentials]]
modId = "forge"
mandatory = true
versionRange = "[44.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.commandessentials]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"
